version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=Qwerty12
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    container_name: sql_data
  velvetech.api:
    image: ${DOCKER_REGISTRY-}velvetechapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - sqldata
  velvetech.web:
    image: ${DOCKER_REGISTRY-}velvetechweb
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - velvetech.api

