version: '3.4'

services:
  velvetech.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL=DockerMsSql    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  velvetech.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APIURL=DockerApiUrl
      - EXTERNALAPIURL=ExternalDockerApiUrl
    ports:
      - "80"

